services:
  chat-service:
    image: samarkinivan/chat-service:latest
    container_name: chat-service
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env
    ports:
      - "8083:8080"
    depends_on:
      - chat-service-db
      - chat-service-redis
    volumes:
      - ./.meta/server/uploads:/uploads

  chat-service-db:
    image: postgres:17
    container_name: chat-service-db
    restart: on-failure
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - ./.meta/postgres/data:/var/lib/postgresql/data

  chat-service-redis:
    image: redis:latest
    container_name: chat-service-redis
    restart: on-failure
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - ./.meta/redis/data:/root/redis
      - ./.meta/redis/conf:/usr/local/etc/redis/redis.conf
